"""
State Management for DeepReason AI Agent

This module defines the AgentState TypedDict that maintains the state
throughout the research workflow using LangGraph.
"""

from typing import TypedDict, List


class AgentState(TypedDict):
    """
    Central state structure for the DeepReason research agent.
    
    This TypedDict maintains all the information that flows through
    the LangGraph workflow nodes.
    """
    # User input query to research
    query: str
    
    # List of search queries generated by the planner
    plan: List[str]
    
    # Accumulated research data from search results
    content: List[str]
    
    # Track number of revision cycles (critic rejections)
    revision_number: int
    
    # Maximum allowed revisions to prevent infinite loops
    max_revisions: int
    
    # Final synthesized research report
    final_report: str
